theme: jekyll-theme-cayman
repository: bennet0496/technicserver

show_releases: true
piwik_analytics: piwik.becker-dd.de/

plugins:
  - jekyll-sitemap
  - jemoji
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
